disabled_rules:
- trailing_whitespace
- trailing_comma

opt_in_rules:
- empty_count
- empty_string
- trailing_closure

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

custom_rules:
    dont_scale_to_zero:
        included: ".*\\.swift"
        name: "Don't scale down to 0."
        regex: "\\.scaleEffect\\([^\\)]*(\\ 0\\ [^\\)]*\\)|0.0(\\ |\\))|\\ 0(\\)|,))"
        message: "Make sure to provide a non-zero number to avoid transformation warnings, such as 'ignoring singular matrix.'"
        severity: error
    use_data_constructor_over_string_member:
        included: ".*\\.swift"
        name: "Do not use String.data(using: .utf8)"
        regex: "\\.?data\\(using: \\.utf8\\)"
        message: "Prefer using Data(string.utf8) over String.data(using: .utf8) since the Data constructor is non-optional, and Strings are guaranteed to be encodable as .utf8."
        severity: error
    duplicate_remove_duplicates:
        included: ".*\\.swift"
        name: "Duplicate `removeDuplicates()`"
        message: "ViewStore's publisher already does `removeDuplicates()`"
        regex: 'publisher\.[^(|{|,]*removeDuplicates\(\)'
        severity: error

nesting:
    type_level:
        warning: 3
        error: 6
    function_level:
        warning: 5
        error: 10

line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
    
function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 4
    error: 6

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

reporter: "xcode"

identifier_name:
    allowed_symbols: "_"